"""create posts module relationship user

Revision ID: 5689510a50db
Revises: 0c381703dd88
Create Date: 2019-02-27 23:09:34.779284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5689510a50db'
down_revision = '0c381703dd88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img_url', sa.String(length=200), nullable=True),
    sa.Column('thumb_url', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
